import { defineStore } from "pinia";

export const useJobsStore = defineStore('jobs',{
    state : () => ({
        data: [
            {
                id : 1,
                posisi : 'Promotor Elektronik',
                no_jo : '029788/ISH/01010107/2023',
                lokasi : 'Tangerang',
                total : 14,
                creator : 'M Nur Alif',
                screening : 2,
                psikotest : 2,
                interview_hr : 2,
                interview_user : 2,
                peralihan : 2,
                reject : 2,
                hiring : 2,
                isPosted : true,
                status : '1',
            },
            {
                id : 2,
                posisi : 'Admin Warehouse',
                no_jo : '029788/ISH/01010106/2023',
                lokasi : 'Jakarta Selatan',
                total : 14,
                creator : 'M Nur Alif',
                screening : 2,
                psikotest : 2,
                interview_hr : 2,
                interview_user : 2,
                peralihan : 2,
                reject : 2,
                hiring : 2,
                isPosted : true,
                status : '1',
            },
            {
                id : 3,
                posisi : 'Digital Marketing',
                no_jo : '029788/ISH/01010105/2023',
                lokasi : 'Depok',
                total : 14,
                creator : 'M Nur Alif',
                screening : 2,
                psikotest : 2,
                interview_hr : 2,
                interview_user : 2,
                peralihan : 2,
                reject : 2,
                hiring : 2,
                isPosted : true,
                status : '1',
            },
            {
                id : 4,
                posisi : 'Sales',
                no_jo : '029788/ISH/01010104/2023',
                lokasi : 'Bekasi',
                total : 14,
                creator : 'M Nur Alif',
                screening : 2,
                psikotest : 2,
                interview_hr : 2,
                interview_user : 2,
                peralihan : 2,
                reject : 2,
                hiring : 2,
                isPosted : true,
                status : '3',
            },
            {
                id : 5,
                posisi : 'Promotor Elektronik',
                no_jo : '029788/ISH/01010107/2023',
                lokasi : 'Tangerang',
                total : 14,
                creator : 'Ojan',
                screening : 2,
                psikotest : 2,
                interview_hr : 2,
                interview_user : 2,
                peralihan : 2,
                reject : 2,
                hiring : 2,
                isPosted : true,
                status : '4',
            },
            {
                id : 6,
                posisi : 'Admin Warehouse',
                no_jo : '029788/ISH/01010106/2023',
                lokasi : 'Jakarta Selatan',
                total : 14,
                creator : 'Putri',
                screening : 2,
                psikotest : 2,
                interview_hr : 2,
                interview_user : 2,
                peralihan : 2,
                reject : 2,
                hiring : 2,
                isPosted : true,
                status : '1',
            },
            {
                id : 7,
                posisi : 'Digital Marketing',
                no_jo : '029788/ISH/01010105/2023',
                lokasi : 'Depok',
                total : 14,
                creator : 'M Chelyna',
                screening : 2,
                psikotest : 2,
                interview_hr : 2,
                interview_user : 2,
                peralihan : 2,
                reject : 2,
                hiring : 2,
                isPosted : true,
                status : '2',
            },
            {
                id : 8,
                posisi : 'Sales',
                no_jo : '029788/ISH/01010104/2023',
                lokasi : 'Bekasi',
                total : 14,
                creator : 'Chelyn',
                screening : 2,
                psikotest : 2,
                interview_hr : 2,
                interview_user : 2,
                peralihan : 2,
                reject : 2,
                hiring : 2,
                isPosted : true,
                status : '3',
            },
            {
                id : 9,
                posisi : 'Promotor Elektronik',
                no_jo : '029788/ISH/01010107/2023',
                lokasi : 'Tangerang',
                total : 14,
                creator : 'M Noer Alif',
                screening : 2,
                psikotest : 2,
                interview_hr : 2,
                interview_user : 2,
                peralihan : 2,
                reject : 2,
                hiring : 2,
                isPosted : true,
                status : '4',
            },
            {
                id : 10,
                posisi : 'Admin Warehouse',
                no_jo : '029788/ISH/01010106/2023',
                lokasi : 'Jakarta Selatan',
                total : 14,
                creator : 'Noer Alif',
                screening : 2,
                psikotest : 2,
                interview_hr : 2,
                interview_user : 2,
                peralihan : 2,
                reject : 2,
                hiring : 2,
                isPosted : false,
                status : '1',
            },
            {
                id : 11,
                posisi : 'Digital Marketing',
                no_jo : '029788/ISH/01010105/2023',
                lokasi : 'Depok',
                total : 14,
                creator : 'M Nur Aji',
                screening : 2,
                psikotest : 2,
                interview_hr : 2,
                interview_user : 2,
                peralihan : 2,
                reject : 2,
                hiring : 2,
                isPosted : false,
                status : '2',
            },
            {
                id : 12,
                posisi : 'Sales',
                no_jo : '029788/ISH/01010104/2023',
                lokasi : 'Bekasi',
                total : 14,
                creator : 'M Nur Aji',
                screening : 2,
                psikotest : 2,
                interview_hr : 2,
                interview_user : 2,
                peralihan : 2,
                reject : 2,
                hiring : 2,
                isPosted : false,
                status : '3',
            },
        ],
        filters:{
            search : '',
            creator : '',
            location : '',
            status : '',
        },
        locations: [],
        creators: [],
    }),
    getters : {
        getByStatus(){
            return this.data.filter((job) => {
                const statusMatch = job.status.toLowerCase().includes(this.filters.status.toLowerCase());
                return statusMatch;
            });
        },
        filteredJobs(){
            return this.data.filter((job) => {
                const statusMatch = job.status.toLowerCase().includes(this.filters.status.toLowerCase());
                const creatorMatch = job.creator.toLowerCase().includes(this.filters.creator.toLowerCase());
                const locationMatch = job.lokasi.toLowerCase().includes(this.filters.location.toLowerCase());
                const joMatch = job.no_jo.toLowerCase().includes(this.filters.search.toLowerCase());
                const posisiMatch = job.posisi.toLowerCase().includes(this.filters.search.toLowerCase());
                const searchMatch = posisiMatch || joMatch;

                return statusMatch && creatorMatch && locationMatch && searchMatch;
            });
        },
        getLocations(){
            return [...new Set(this.data.map(job => job.lokasi))];
        },
        getCreators(){
            return [...new Set(this.data.map(job => job.creator))];
        },
        getStatus(){
            return [...new Set(this.data.map(job => job.status))];
        },
    },
    actions : {
        updateFilter(column, value) {
            this.filters[column] = value;
        },
    },
    
})