import { defineStore } from "pinia";

export const useScheduleStore = defineStore("schedule",{
    state : () => ({
        data: [
            {
                id: 1,
                date: '2024-01-25', //year-month-date
                time_start: '18:00', //24 Format
                time_end: '22:00',
                activity: 'Interview HR',
                applicantId: 1,
                detail: `Interview HR menggunakan Zoom Secara Online, dengan  busana rapih sopan dan menyiapkan berkas / portofolio`,
                link_meet: 'https://meet.google.com/kashdjkklqwek',
                jobId: 3,
                created: '2024-01-24 18:55',
                updated: '2024-01-24 19:55',
            },
            {
                id: 2,
                date: '2024-01-26',
                time_start: '15:30',
                time_end: '17:30',
                activity: 'Technical Test',
                applicantId: 2,
                detail: 'Melakukan uji teknis sebagai bagian dari proses seleksi',
                link_meet: 'https://meet.google.com/xyzabc123',
                jobId: 1,
                created: '2024-01-25 14:30',
                updated: '2024-01-25 16:00',
            },
            {
                id: 3,
                date: '2024-01-27',
                time_start: '10:00',
                time_end: '12:00',
                activity: 'Interview User',
                applicantId: 3,
                detail: 'Wawancara dengan tim pengguna untuk menilai keterampilan interpersonal',
                link_meet: 'https://meet.google.com/pqrst987',
                jobId: 2,
                created: '2024-01-26 09:45',
                updated: '2024-01-26 11:30',
            },
            {
                id: 4,
                date: '2024-01-28',
                time_start: '14:00',
                time_end: '16:00',
                activity: 'Presentation',
                applicantId: 4,
                detail: 'Presentasi keterampilan dan pengalaman yang dimiliki',
                link_meet: 'https://meet.google.com/uvwxyz456',
                jobId: 4,
                created: '2024-01-27 13:45',
                updated: '2024-01-27 15:30',
            },
            {
                id: 5,
                date: '2024-01-29',
                time_start: '09:30',
                time_end: '11:30',
                activity: 'Group Discussion',
                applicantId: 5,
                detail: 'Diskusi kelompok untuk menilai kemampuan bekerja dalam tim',
                link_meet: 'https://meet.google.com/abcd123efg',
                jobId: 3,
                created: '2024-01-28 08:45',
                updated: '2024-01-28 10:45',
            },
            {
                id: 6,
                date: '2024-01-30',
                time_start: '16:30',
                time_end: '18:30',
                activity: 'Interview HR',
                applicantId: 6,
                detail: 'Wawancara dengan Human Resources untuk penilaian lebih lanjut',
                link_meet: 'https://meet.google.com/ijkl678mno',
                jobId: 1,
                created: '2024-01-29 15:55',
                updated: '2024-01-29 17:30',
            },
            {
                id: 7,
                date: '2024-02-01',
                time_start: '11:00',
                time_end: '13:00',
                activity: 'Technical Test',
                applicantId: 7,
                detail: 'Melakukan uji teknis sebagai bagian dari proses seleksi',
                link_meet: 'https://meet.google.com/pqrs789tuv',
                jobId: 2,
                created: '2024-01-31 10:30',
                updated: '2024-01-31 12:15',
            },
            {
                id: 8,
                date: '2024-02-02',
                time_start: '14:30',
                time_end: '16:30',
                activity: 'Presentation',
                applicantId: 8,
                detail: 'Presentasi keterampilan dan pengalaman yang dimiliki',
                link_meet: 'https://meet.google.com/wxyz345abc',
                jobId: 4,
                created: '2024-02-01 13:45',
                updated: '2024-02-01 15:30',
            },
            {
                id: 9,
                date: '2024-02-03',
                time_start: '09:30',
                time_end: '11:30',
                activity: 'Group Discussion',
                applicantId: 9,
                detail: 'Diskusi kelompok untuk menilai kemampuan bekerja dalam tim',
                link_meet: 'https://meet.google.com/defg456hij',
                jobId: 3,
                created: '2024-02-02 08:45',
                updated: '2024-02-02 10:45',
            },
            {
                id: 10,
                date: '2024-02-04',
                time_start: '16:30',
                time_end: '18:30',
                activity: 'Interview HR',
                applicantId: 10,
                detail: 'Wawancara dengan Human Resources untuk penilaian lebih lanjut',
                link_meet: 'https://meet.google.com/ghij678klm',
                jobId: 1,
                created: '2024-02-03 15:55',
                updated: '2024-02-03 17:30',
            },
            {
                id: 11,
                date: '2024-02-05',
                time_start: '11:00',
                time_end: '13:00',
                activity: 'Technical Test',
                applicantId: 11,
                detail: 'Melakukan uji teknis sebagai bagian dari proses seleksi',
                link_meet: 'https://meet.google.com/ijkl789mno',
                jobId: 2,
                created: '2024-02-04 10:30',
                updated: '2024-02-04 12:15',
            },
            {
                id: 12,
                date: '2024-02-06',
                time_start: '14:30',
                time_end: '16:30',
                activity: 'Presentation',
                applicantId: 12,
                detail: 'Presentasi keterampilan dan pengalaman yang dimiliki',
                link_meet: 'https://meet.google.com/ghij890klm',
                jobId: 4,
                created: '2024-02-05 13:45',
                updated: '2024-02-05 15:30',
            },
            {
                id: 13,
                date: '2024-02-07',
                time_start: '09:30',
                time_end: '11:30',
                activity: 'Group Discussion',
                applicantId: 13,
                detail: 'Diskusi kelompok untuk menilai kemampuan bekerja dalam tim',
                link_meet: 'https://meet.google.com/klmn901opq',
                jobId: 3,
                created: '2024-02-06 08:45',
                updated: '2024-02-06 10:45',
            },
            {
                id: 14,
                date: '2024-02-08',
                time_start: '16:30',
                time_end: '18:30',
                activity: 'Interview HR',
                applicantId: 14,
                detail: 'Wawancara dengan Human Resources untuk penilaian lebih lanjut',
                link_meet: 'https://meet.google.com/pqrs123tuv',
                jobId: 1,
                created: '2024-02-07 15:55',
                updated: '2024-02-07 17:30',
            },
        ],
        filters:{
            month : '',
            year : '',
            activity : '',
        },
    }),
    getters : {
        filteredSchedules(){
            return this.data.filter((schedule) => {
                const activityMatch = schedule.activity.toLowerCase().includes(this.filters.activity.toLowerCase());
                const monthMatch = !this.filters.month || new Date(schedule.date).getMonth() + 1 === parseInt(this.filters.month);
                const yearMatch = !this.filters.year || new Date(schedule.date).getFullYear() === parseInt(this.filters.year);
        
                return activityMatch && monthMatch && yearMatch;
            });
        },
    },
    actions : {
        updateFilter(column, value) {
            this.filters[column] = value;
        },
    },
    
})